### PR TITLE
Update API to v0.6.7, fix HA 2024.1 compatibility

### PR DESCRIPTION
**Pull request by Rijswijker**
- Replace deprecated constants to fix warnings in HA 2024.1
- Update API version to 0.6.7

**Fixes:**
- Fixes ualex73/slide#12
- Fixes ualex73/slide#10
- Fixes ualex73/slide#9
- Fixes ualex73/slide#8

### CODE REVIEW

**Comment by hugo-leij** [comment]
Hi @Rijswijker 

Thnx for the changes, I tried it but got the following error. PS I use the local API not the cloud version.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/slide/cover.py", line 62, in async_setup_platform
    slide = await hass.data[DOMAIN][API_LOCAL].slide_info(config.get(CONF_HOST))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/goslideapi/goslideapi.py", line 688, in slide_info
    result = await self._request(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/goslideapi/goslideapi.py", line 628, in _request
    respstatus, resptext = await self._dorequest(
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/goslideapi/goslideapi.py", line 577, in _dorequest
    raise ClientTimeoutError("Connection Timeout") from None
goslideapi.goslideapi.ClientTimeoutError: Connection Timeout
```

**Comment by Rijswijker** [comment]
Hi i didn't own the slide by my own, i have fix the issue for a friend of my.
I think there is a difference in the `configuration.yaml`

His `configuration.yaml` looks like this:
```
cover:
  - platform: slide
    host: IP_ADDRESS
    password: CODE_ON_SLIDE
    api_version: 2
```

**Comment by hugo-leij** [comment]
I had api version 1, just changed it to number 2 but still te same error.

Logbook:
```
2024-04-28 14:13:39.866 INFO (MainThread) [custom_components.slide] Slide Cloud API not configured
2024-04-28 14:13:39.867 DEBUG (MainThread) [goslideapi.goslideapi] REQ-L1: API=http://10.0.1.26/rpc/Slide.GetInfo, type=POST, data=null

~~~

2024-04-28 14:13:50.242 WARNING (MainThread) [homeassistant.components.cover] Setup of cover platform slide is taking over 10 seconds.
2024-04-28 14:13:52.317 ERROR (MainThread) [homeassistant.components.cover] Error while setting up slide platform for cover
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/slide/cover.py", line 62, in async_setup_platform
slide = await hass.data[DOMAIN][API_LOCAL].slide_info(config.get(CONF_HOST))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/goslideapi/goslideapi.py", line 688, in slide_info
result = await self._request(
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/goslideapi/goslideapi.py", line 628, in _request
respstatus, resptext = await self._dorequest(
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/goslideapi/goslideapi.py", line 577, in _dorequest
raise ClientTimeoutError("Connection Timeout") from None
goslideapi.goslideapi.ClientTimeoutError: Connection Timeout
```

**Comment by Rijswijker** [comment]
Did you also update the manifest.json to 0.6.7?

If so, I think I can't help you unfortunately since I don't own the slide myself.
It still works for that friend of mine, and I don't know what any differences might be.
I had hoped to help other people with this change, but alas.

**Comment by hugo-leij** [comment]
@Rijswijker 

I restored the old version, but it get the same error. So something else seems to be going on 🤔

**Comment by hugo-leij** [comment]
My slide was down :-(, did a reset and the local api is working again. Only on api_version 2 it doenst work at my side (old Slide, old firmware?). 

So put back at line 60
`
config.get(CONF_API_VERSION),
`

And set goslide to 0.6.6. (i think 0.6.7 force api 2).

For now, it's working local, I will send Slide a mail what the différance is. I will post there reaction here :-)

**Comment by hugo-leij** [comment]
For now no further updates:

_Hi hugo,

[English below]

Dit is een automatisch antwoord van mij, Kaj, oprichter van Slide. Op het moment ondervinden wij een probleem met de productie van nieuwe Slides waardoor wij nu al een tijd geen voorraad hebben. Dit probleem is zo groot geworden dat wij de kosten hebben moeten minimaliseren om de continuïteit van de onderneming te kunnen waarborgen. Hierdoor is er geen personeel meer op de supportafdeling aanwezig en zijn wij helaas niet in staat vragen binnen korte termijn te beantwoorden. Dit doet mij erg spijt omdat ik service altijd erg belangrijk vind. Bij deze dan ook mijn excuses voor deze manier van communiceren. Wij werken hard aan een oplossing en we hopen snel weer aan onze eigen eisen betreft support te kunnen voldoen.

Ter geruststelling wellicht, alle Slides zullen het blijven doen, ook in het meest negatieve scenario waarin de onderneming de lopende kosten niet meer kan dekken. Wij werken uiteraard hard om dit scenario niet uit te laten komen.

Nogmaals mijn excuses voor de noodzaak van dit bericht,

Groet,

Kaj Beetstra, oprichter van slide

-----
Hi hugo,

This is an automatic response from me, Kaj, founder of Slide. We are currently experiencing a problem with the production of new Slides, which means we have been out of stock for some time now. This problem has become so serious that we have had to minimize costs to ensure the continuity of the company. As a result, there is no longer any staff in the support department and we are unfortunately unable to answer questions within a short period of time. This makes me very sorry because I believe service to be very important. My apologies for this way of communicating. We are working hard on a solution and we hope to be able to meet our own support requirements again soon.

To reassure you perhaps, all Slides will continue to work, even in the most negative scenario in which the company can no longer cover its running costs. We are of course working hard to prevent this scenario from happening.

Once again my apologies for having to write and send you this message,

Best regards,

Kaj Beetstra, founder of Slide_

**Pull request merged**
